### ISSUE TITLE
在 Firefox 53 上失效了？

### ISSUE THREAD

**Issue by nicolas-yangli** [hrimfaxi/autoproxy-ng#7]
我这里比较诡异，在 2017-04-25 CST 突然失效的，重置 firefox 后能起作用一会儿，但很快又失效。

先怀疑是其他附加组件干扰，试过把其他扩展全部卸载一个个装，但也没排查出是哪里有问题。

在「选项」- 「高级」里面点击设置代理的按钮，显示的是 Firefox 原来的代理配置。

**Comment by yfdyh000** [comment]
AutoProxy（各修复版）在 Firefox 52/53 开始有bug，不时会有规则失效或规则组错误的问题。

**Comment by RuralHunter** [comment]
官方版本刚更新到0.55了，我装了一下似乎好了。

**Comment by nicolas-yangli** [comment]
对，可以 close 了

Rural Hunter <notifications@github.com>于2017年4月28日周五 上午9:49写道：
